# --- cert-manager + TLS certificate issuance for 'saas minio'. Same scope as services/vault/lib/tls.sh
# (self-signed / letsencrypt http01 / letsencrypt dns01 cloudflare only): no DuckDNS webhook here,
# same reasoning as vault's own choice not to extend gitlab's one deliberate webhook exception to a
# second service without an equally explicit decision (see CLAUDE.md).
#
# MinIO serves its S3 API (9000) and web console (9001) on different ports behind one Ingress
# controller, so it needs two hostnames sharing one Certificate: the console at DOMAIN, the S3 API
# at 's3.DOMAIN' (see install.sh), both as SANs on the same Certificate/Secret (same EXTRA_SAN
# pattern as services/gitlab/lib/tls.sh's registry.<domain>/pages.<domain>).

_saas_minio_valid_tls_mode()     { [[ "$1" == "self-signed" || "$1" == "letsencrypt" ]]; }
_saas_minio_valid_challenge()    { [[ "$1" == "http01" || "$1" == "dns01" ]]; }
_saas_minio_valid_dns_provider() { [[ "$1" == "cloudflare" ]]; }

# cert-manager's own idempotent install lives in lib/common.sh as _saas_ensure_certmanager, shared
# with gitlab/vault. Everything below (issuers, certificate requests) stays here: it genuinely
# differs per service (domains, SANs, which challenge types are offered).

# _saas_minio_certmanager_issuer_selfsigned NAME
_saas_minio_certmanager_issuer_selfsigned() {
    local name="$1"
    kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${name}
spec:
  selfSigned: {}
EOF
}

# _saas_minio_certmanager_issuer_letsencrypt_http01 NAME EMAIL INGRESS_CLASS [SERVER]
_saas_minio_certmanager_issuer_letsencrypt_http01() {
    local name="$1" email="$2" ingress_class="$3" server="${4:-https://acme-v02.api.letsencrypt.org/directory}"
    kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${name}
spec:
  acme:
    server: ${server}
    email: ${email}
    privateKeySecretRef: {name: ${name}-account-key}
    solvers:
      - http01:
          ingress: {ingressClassName: ${ingress_class}}
EOF
}

# _saas_minio_certmanager_issuer_letsencrypt_dns01_cloudflare NAME EMAIL TOKEN [SERVER]
# TOKEN: a Cloudflare API Token with Zone:DNS:Edit permission for the domain's zone (not the Global API Key).
_saas_minio_certmanager_issuer_letsencrypt_dns01_cloudflare() {
    local name="$1" email="$2" token="$3" server="${4:-https://acme-v02.api.letsencrypt.org/directory}"

    kubectl -n cert-manager create secret generic "${name}-cloudflare-token" \
        --from-literal=api-token="$token" \
        --dry-run=client -o yaml | kubectl apply -f - >/dev/null || return 1

    kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${name}
spec:
  acme:
    server: ${server}
    email: ${email}
    privateKeySecretRef: {name: ${name}-account-key}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef: {name: ${name}-cloudflare-token, key: api-token, namespace: cert-manager}
EOF
}

# _saas_minio_certificate_request NAMESPACE NAME DOMAIN ISSUER SECRET_NAME [EXTRA_SAN...]
# Creates/updates a Certificate and waits (up to 180s) for it to become Ready. Same quoting of every
# dnsName as services/gitlab/lib/tls.sh's certificate_request (a leading '*' would otherwise be
# YAML's alias indicator; harmless no-op for a plain hostname).
_saas_minio_certificate_request() {
    local ns="$1" name="$2" domain="$3" issuer="$4" secret_name="$5"
    shift 5
    local -a dns_names=("$domain" "$@")

    local dns_names_yaml="" d
    for d in "${dns_names[@]}"; do
        dns_names_yaml+="\"${d}\","
    done
    dns_names_yaml="${dns_names_yaml%,}"

    kubectl -n "$ns" apply -f - <<EOF || return 1
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${name}
spec:
  secretName: ${secret_name}
  dnsNames: [${dns_names_yaml}]
  issuerRef: {name: ${issuer}, kind: ClusterIssuer}
EOF

    _saas_log_wait "Waiting for the TLS certificate for ${domain} (issuer: ${issuer})…"
    kubectl -n "$ns" wait --for=condition=Ready --timeout=180s "certificate/${name}"
}

# _saas_minio_ingress_apply NAMESPACE RELEASE DOMAIN S3_DOMAIN INGRESS_CLASS TLS_SECRET
# MinIO has no Helm chart here (plain manifests, see backend.sh), so unlike gitlab/vault its
# Ingress isn't generated by a chart's own values overlay: this function creates it directly. Two
# hosts on one Ingress since the console (9001) and the S3 API (9000) are different ports: the
# console at DOMAIN, the S3 API at S3_DOMAIN, both trusted by the one Certificate _saas_minio_certificate_request already issued for both names.
_saas_minio_ingress_apply() {
    local ns="$1" release="$2" domain="$3" s3_domain="$4" ingress_class="$5" tls_secret="$6"
    kubectl -n "$ns" apply -f - <<EOF || return 1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${release}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: ${ingress_class}
  tls:
    - hosts: ["${domain}", "${s3_domain}"]
      secretName: ${tls_secret}
  rules:
    - host: ${domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: {service: {name: ${release}, port: {number: 9001}}}
    - host: ${s3_domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: {service: {name: ${release}, port: {number: 9000}}}
EOF
}
