# --- 'saas cluster create': creates a new local Kubernetes cluster.

_saas_cluster_create_help() {
    cat <<'EOF'
Usage: saas cluster create [OPTIONS]

Creates a new local Kubernetes cluster.

Every option that's omitted (except -y/--yes or --non-interactive) is
asked interactively, suggesting the default value in brackets (or as a
numbered '0)' option for a closed set of values); an explicit flag is
never asked again, but is still validated the same way.

Options:
      --provider NAME          Cluster provider (default: kind, the only
                              one implemented today; reserved for a future
                              remote provider, see 'Providers' below)
  -n, --name NAME              Cluster name (if omitted, asked or
                              autogenerated as kind-YYYYMMDD-HHMMSS)
  -w, --workers N               Number of worker nodes besides the
                              control-plane (default: 1;
                              SAAS_CLUSTER_WORKERS)
      --image IMAGE             kind node image to use (default: whatever
                              kind ships with)
      --loadbalancer            Install MetalLB on the cluster (default)
      --no-loadbalancer         Don't install MetalLB
      --storage-mode MODE       local-path (default) or nfs, see
                              'Storage modes' below
      --storage-fix             (local-path mode only) Enables the
                              extraMounts fix so storage works across
                              several nodes (default)
      --no-storage-fix          (local-path mode only) Disables the fix,
                              reproducing kind's own broken multi-node
                              behavior
      --storage-dir PATH        Host directory where the storage data
                              lives (default: ~/.local/share/kind-cluster)
      --expose-mode MODE        none (default), ingress-nginx or
                              gateway-api, see 'Exposure modes' below
  -p, --port-map HOSTPORT:CONTAINERPORT[/tcp|udp]
                              Maps a host port to the control-plane.
                              Repeatable. Incompatible with HOSTPORT 80/443
                              if --expose-mode isn't 'none' (reserved).
      --lb-range START-END      Manual IP range for MetalLB's pool, instead
                              of computing it automatically
  -y, --yes                     Don't ask anything; use the
                              default/autogenerated values with no
                              confirmation
      --non-interactive         Same as --yes for the fill-in prompts
                              (create has no destructive confirmation)
  -h, --help                    Show this help

Providers (--provider):
  kind (default, the only one implemented today)  A local cluster via the
                              'kind' CLI (Docker-based Kubernetes nodes).
                              Every other option above applies to this
                              provider. A future remote provider is added
                              as a new accepted --provider value, with its
                              own flags validated only when selected;
                              'create'/'delete'/'list'/'status'/'use'
                              themselves aren't expected to be renamed or
                              restructured for it (see CLAUDE.md's Design
                              notes for services/cluster/).

Storage modes (--storage-mode):
  local-path (default)        kind's own local-path-provisioner, with the
                              same host directory mounted on every node
                              (--storage-fix). Simple, no extra
                              components, but a pod rescheduled to another
                              node stays Pending: the nodeAffinity each PV
                              records is immutable in current Kubernetes
                              (no patch fixes this; see CLAUDE.md's Design
                              notes).
  nfs                          Installs an NFS server plus csi-driver-nfs
                              as the default StorageClass. No
                              nodeAffinity: rescheduling across nodes just
                              works. Heavier (one NFS pod plus an extra
                              Helm chart). The option to pick if a pod
                              needs to survive losing its node.

Exposure modes (--expose-mode):
  none (default)               Installs no ingress-controller or Gateway
                              API. Exposing services via --loadbalancer
                              (MetalLB) or --port-map is still available.
  ingress-nginx                Installs ingress-nginx via Helm, pinned to
                              the control-plane node with hostPort 80/443
                              (like kind's own official manifest).
                              Reserves the host's 80/443 ports.
  gateway-api                  Installs Envoy Gateway via Helm (includes
                              the Gateway API CRDs, standard channel), with
                              a Gateway already configured (fixed NodePort
                              30080/30443, mapped to the host's 80/443).
                              The modern alternative to a classic
                              ingress-controller.
  Combining --expose-mode with --loadbalancer isn't required: a real
  deployment usually picks a single HTTP exposure strategy
  (ingress/Gateway API) and reserves LoadBalancer Services for traffic
  that genuinely needs its own IP (non-HTTP).

Environment variables:
  SAAS_CLUSTER_NAME, SAAS_CLUSTER_WORKERS, SAAS_CLUSTER_IMAGE,
  SAAS_CLUSTER_LOADBALANCER, SAAS_CLUSTER_STORAGE_FIX,
  SAAS_CLUSTER_STORAGE_MODE, SAAS_CLUSTER_STORAGE_DIR,
  SAAS_CLUSTER_EXPOSE_MODE, SAAS_CLUSTER_LB_POOL_SIZE,
  SAAS_CLUSTER_NON_INTERACTIVE
  (see 'saas cluster --help' for what each one means)

Examples:
  saas cluster create
  saas cluster create --name my-cluster --workers 2
  saas cluster create --name no-lb --no-loadbalancer
  saas cluster create --name with-nfs --storage-mode nfs
  saas cluster create --name with-ingress --expose-mode ingress-nginx
  saas cluster create --name with-gateway --expose-mode gateway-api
  saas cluster create --name ci --workers 2 --yes
  saas cluster create -p 8080:80 -p 8443:443
EOF
}

# _saas_cluster_rollback NAME STORAGE_DIR
_saas_cluster_rollback() {
    local name="$1" storage_dir="$2"
    kind delete cluster --name "$name" >/dev/null 2>&1
    if [ -n "$storage_dir" ] && [ -n "$name" ]; then
        rm -rf "${storage_dir:?}/${name}"
    fi
}

_saas_cluster_create() {
    local provider="kind"
    local name="${SAAS_CLUSTER_NAME:-}" workers="${SAAS_CLUSTER_WORKERS:-1}" image="${SAAS_CLUSTER_IMAGE:-}"
    local loadbalancer="${SAAS_CLUSTER_LOADBALANCER:-true}"
    local storage_fix="${SAAS_CLUSTER_STORAGE_FIX:-true}"
    local storage_mode="${SAAS_CLUSTER_STORAGE_MODE:-local-path}"
    local storage_dir="${SAAS_CLUSTER_STORAGE_DIR:-$HOME/.local/share/kind-cluster}"
    local expose_mode="${SAAS_CLUSTER_EXPOSE_MODE:-none}"
    local lb_range=""
    local -a port_maps=()
    local yes=false non_interactive="${SAAS_CLUSTER_NON_INTERACTIVE:-false}"
    local workers_set=false image_set=false loadbalancer_set=false lb_range_set=false
    local storage_mode_set=false storage_fix_set=false storage_dir_set=false
    local expose_mode_set=false port_maps_set=false

    local args
    args=$(getopt -o n:w:p:yh -l provider:,name:,workers:,image:,loadbalancer,no-loadbalancer,storage-fix,no-storage-fix,storage-mode:,storage-dir:,expose-mode:,port-map:,lb-range:,yes,non-interactive,help --name saas_cluster_create -- "$@") || {
        _saas_cluster_create_help; return 1
    }
    eval set -- "$args"

    while true; do
        case "$1" in
            --provider)          provider="$2"; shift 2 ;;
            -n|--name)          name="$2"; shift 2 ;;
            -w|--workers)       workers="$2"; workers_set=true; shift 2 ;;
            --image)            image="$2"; image_set=true; shift 2 ;;
            --loadbalancer)     loadbalancer=true; loadbalancer_set=true; shift ;;
            --no-loadbalancer)  loadbalancer=false; loadbalancer_set=true; shift ;;
            --storage-fix)      storage_fix=true; storage_fix_set=true; shift ;;
            --no-storage-fix)   storage_fix=false; storage_fix_set=true; shift ;;
            --storage-mode)     storage_mode="$2"; storage_mode_set=true; shift 2 ;;
            --storage-dir)      storage_dir="$2"; storage_dir_set=true; shift 2 ;;
            --expose-mode)      expose_mode="$2"; expose_mode_set=true; shift 2 ;;
            -p|--port-map)      port_maps+=("$2"); port_maps_set=true; shift 2 ;;
            --lb-range)         lb_range="$2"; lb_range_set=true; shift 2 ;;
            -y|--yes)           yes=true; shift ;;
            --non-interactive)  non_interactive=true; shift ;;
            -h|--help)          _saas_cluster_create_help; return 0 ;;
            --)                 shift; break ;;
        esac
    done
    $yes && non_interactive=true

    _saas_cluster_valid_provider "$provider" || {
        _saas_log_err "--provider must be 'kind' (the only provider implemented today; got: '$provider')."
        return 1
    }

    # From here on, every option is resolved (a flag already given takes
    # priority over a prompt) and validated on the spot - an invalid value
    # typed at a prompt is re-asked (a bounded loop inside the helpers),
    # instead of aborting all of 'create' with one big validation block at
    # the end.

    if [ -z "$name" ]; then
        local default_name
        default_name="kind-$(date +%Y%m%d-%H%M%S)"
        name="$(_saas_prompt "Cluster name" "$default_name" "$non_interactive")"
    fi

    if $workers_set; then
        _saas_cluster_valid_workers "$workers" || {
            _saas_log_err "--workers must be an integer >= 0 (got: '$workers')."
            return 1
        }
    else
        workers="$(_saas_prompt_validated "Number of worker nodes" "$workers" "$non_interactive" \
            "--workers must be an integer >= 0" _saas_cluster_valid_workers)" || return 1
    fi

    if ! $image_set; then
        local image_hint image_label="kind node image (Kubernetes version; empty = whatever kind ships with)"
        image_hint="$(_saas_cluster_default_node_image_hint)"
        [ -n "$image_hint" ] && image_label="kind node image (Kubernetes version; empty = whatever kind ships with, currently ${image_hint})"
        image="$(_saas_prompt "$image_label" "$image" "$non_interactive")"
    fi

    $loadbalancer_set || loadbalancer="$(_saas_prompt_bool "Install MetalLB (LoadBalancer)" "$loadbalancer" "$non_interactive")"

    if $loadbalancer; then
        if $lb_range_set; then
            _saas_cluster_valid_lb_range "$lb_range" || {
                _saas_log_err "--lb-range must have the format START-END (IPs), e.g. 172.19.0.200-172.19.0.209 (got: '$lb_range')."
                return 1
            }
        else
            lb_range="$(_saas_prompt_validated "IP range for MetalLB (START-END, empty = auto)" "$lb_range" "$non_interactive" \
                "The range must have the format START-END (IPs)" _saas_cluster_valid_lb_range)" || return 1
        fi
    fi

    if $storage_mode_set; then
        _saas_cluster_valid_storage_mode "$storage_mode" || {
            _saas_log_err "--storage-mode must be 'local-path' or 'nfs' (got: '$storage_mode')."
            return 1
        }
    else
        storage_mode="$(_saas_prompt_menu "Storage mode" "$storage_mode" "$non_interactive" local-path nfs)"
    fi

    if [ "$storage_mode" = "local-path" ]; then
        $storage_fix_set || storage_fix="$(_saas_prompt_bool "Apply the multi-node storage fix (extraMounts)" "$storage_fix" "$non_interactive")"
    fi

    if $storage_dir_set; then
        _saas_cluster_valid_storage_dir "$storage_dir" || {
            _saas_log_err "--storage-dir can't be empty."
            return 1
        }
    else
        storage_dir="$(_saas_prompt_validated "Storage directory on the host" "$storage_dir" "$non_interactive" \
            "--storage-dir can't be empty" _saas_cluster_valid_storage_dir)" || return 1
    fi

    if $expose_mode_set; then
        _saas_cluster_valid_expose_mode "$expose_mode" || {
            _saas_log_err "--expose-mode must be 'none', 'ingress-nginx' or 'gateway-api' (got: '$expose_mode')."
            return 1
        }
    else
        expose_mode="$(_saas_prompt_menu "HTTP exposure mode" "$expose_mode" "$non_interactive" none ingress-nginx gateway-api)"
    fi

    if $port_maps_set; then
        local pm
        for pm in "${port_maps[@]}"; do
            _saas_cluster_valid_port_map "$pm" || {
                _saas_log_err "--port-map '$pm' doesn't have the format HOSTPORT:CONTAINERPORT[/tcp|udp]."
                return 1
            }
        done
    else
        local pm_input pm attempt
        local -a parsed_maps=()
        for attempt in 1 2 3 4 5; do
            pm_input="$(_saas_prompt "Extra port mappings HOSTPORT:CONTAINERPORT[/tcp|udp] (comma-separated, empty = none)" "" "$non_interactive")"
            if [ -z "$pm_input" ]; then
                parsed_maps=()
                break
            fi

            local -a candidate_maps=() cleaned=()
            local valid=true
            IFS=',' read -ra candidate_maps <<< "$pm_input"
            for pm in "${candidate_maps[@]}"; do
                pm="${pm//[[:space:]]/}"
                [ -z "$pm" ] && continue
                if ! _saas_cluster_valid_port_map "$pm"; then
                    _saas_log_err "'$pm' doesn't have the format HOSTPORT:CONTAINERPORT[/tcp|udp]."
                    valid=false
                    break
                fi
                cleaned+=("$pm")
            done

            if $valid; then
                parsed_maps=("${cleaned[@]}")
                break
            fi

            { $non_interactive || [ ! -t 0 ] || [ "$attempt" -eq 5 ]; } && return 1
        done
        port_maps=("${parsed_maps[@]}")
    fi

    if [ "$expose_mode" != "none" ]; then
        local pm hostport
        for pm in "${port_maps[@]}"; do
            hostport="${pm%%:*}"
            if [ "$hostport" = "80" ] || [ "$hostport" = "443" ]; then
                _saas_log_err "--port-map ${pm} collides with the ports reserved by --expose-mode ${expose_mode} (80/443)."
                return 1
            fi
        done
    fi

    if $loadbalancer || [ "$storage_mode" = "nfs" ] || [ "$expose_mode" != "none" ]; then
        _saas_cluster_check_deps full || return 1
    fi

    if kind get clusters -q 2>/dev/null | grep -qx "$name"; then
        _saas_log_err "A kind cluster named '$name' already exists. Use --name to pick another, or 'saas cluster delete $name' first."
        return 1
    fi

    _saas_cluster_check_inotify

    _saas_log_step "Creating cluster '${name}' (${workers} worker(s), storage: ${storage_mode})..."

    local kind_config_file
    kind_config_file="$(mktemp "${TMPDIR:-/tmp}/saas-cluster-XXXXXX.yaml")" \
        || { _saas_log_err "Could not create a temporary file."; return 1; }
    _saas_cluster_render_kind_config "$name" "$workers" "$storage_mode" "$storage_fix" "$storage_dir" "$expose_mode" "${port_maps[@]}" > "$kind_config_file" \
        || { rm -f "$kind_config_file"; return 1; }

    local -a create_args=(--name "$name" --config "$kind_config_file")
    [ -n "$image" ] && create_args+=(--image "$image")

    # kind/kubeadm can fail transiently starting the control-plane under
    # Docker load (e.g. creating a second cluster while another one already
    # has MetalLB running and generating iptables traffic) without it being
    # a real problem with the resulting cluster; retried once before giving
    # up.
    local create_ok=false attempt
    for attempt in 1 2; do
        if kind create cluster "${create_args[@]}"; then
            create_ok=true
            break
        fi
        if [ "$attempt" -eq 1 ]; then
            _saas_log_warn "Cluster creation failed (possibly a startup timeout under Docker load). Retrying in 10s..."
            kind delete cluster --name "$name" >/dev/null 2>&1
            sleep 10
        fi
    done
    rm -f "$kind_config_file"
    if ! $create_ok; then
        _saas_log_err "Failed to create the cluster after retrying."
        _saas_cluster_rollback "$name" "$storage_dir"
        return 1
    fi

    # The cluster itself is NOT rolled back if these steps fail (see
    # CLAUDE.md's Design notes): they're post-creation extras and the user
    # can retry them with 'deploy-loadbalancer' or check 'status'. But
    # 'create''s own exit code must still reflect the failure, so a cluster
    # with broken MetalLB or NFS storage isn't accepted as fine by
    # scripts/CI using '&&'.
    local post_create_failed=false

    if [ "$storage_mode" = "nfs" ]; then
        _saas_cluster_setup_storage_nfs "$name" \
            || { _saas_log_warn "The cluster was created but NFS storage failed. Check with 'saas cluster status $name'."; post_create_failed=true; }
    fi

    if $loadbalancer; then
        _saas_cluster_install_metallb "$name" "$lb_range" \
            || { _saas_log_warn "The cluster was created but MetalLB failed. Retry with 'saas cluster deploy-loadbalancer $name'."; post_create_failed=true; }
    fi

    if [ "$expose_mode" = "ingress-nginx" ]; then
        _saas_cluster_install_ingress_nginx "$name" \
            || { _saas_log_warn "The cluster was created but ingress-nginx failed. Check with 'saas cluster status $name'."; post_create_failed=true; }
    elif [ "$expose_mode" = "gateway-api" ]; then
        _saas_cluster_install_gateway_api "$name" \
            || { _saas_log_warn "The cluster was created but Gateway API (Envoy Gateway) failed. Check with 'saas cluster status $name'."; post_create_failed=true; }
    fi

    if $post_create_failed; then
        _saas_log_warn "Cluster '${name}' created but with failed components. Context: kind-${name}"
        return 1
    fi

    _saas_log_ok "Cluster '${name}' ready. Context: kind-${name}"
}
