# --- saas cluster: manage local Kubernetes clusters with kind (subcommand dispatcher, alias: 'saas k8s'). All paths are resolved relative to this file (BASH_SOURCE), never hardcoded.
#
# v1.0: a faithful, point-by-point port of the 'kind_cluster' bash function
# (maintained separately, in a sibling repo, referenced only by name, never
# by any PC's absolute path) into this repo, so local-saas is self-contained
# by default. See CLAUDE.md's Design notes for services/cluster/ for the
# --provider extension point and the USE_KIND_CLUSTER_FUNCTION transition
# mechanism used by 'saas gitlab|vault|minio'.

_SAAS_CLUSTER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# shellcheck source=lib/deps.sh
source "$_SAAS_CLUSTER_DIR/lib/deps.sh"
# shellcheck source=lib/validators.sh
source "$_SAAS_CLUSTER_DIR/lib/validators.sh"
# shellcheck source=lib/network.sh
source "$_SAAS_CLUSTER_DIR/lib/network.sh"
# shellcheck source=lib/target.sh
source "$_SAAS_CLUSTER_DIR/lib/target.sh"
# shellcheck source=lib/render.sh
source "$_SAAS_CLUSTER_DIR/lib/render.sh"
# shellcheck source=lib/metallb.sh
source "$_SAAS_CLUSTER_DIR/lib/metallb.sh"
# shellcheck source=lib/ingress.sh
source "$_SAAS_CLUSTER_DIR/lib/ingress.sh"
# shellcheck source=lib/storage.sh
source "$_SAAS_CLUSTER_DIR/lib/storage.sh"
# shellcheck source=lib/expose.sh
source "$_SAAS_CLUSTER_DIR/lib/expose.sh"
# shellcheck source=lib/create.sh
source "$_SAAS_CLUSTER_DIR/lib/create.sh"
# shellcheck source=lib/delete.sh
source "$_SAAS_CLUSTER_DIR/lib/delete.sh"
# shellcheck source=lib/list.sh
source "$_SAAS_CLUSTER_DIR/lib/list.sh"
# shellcheck source=lib/status.sh
source "$_SAAS_CLUSTER_DIR/lib/status.sh"
# shellcheck source=lib/use.sh
source "$_SAAS_CLUSTER_DIR/lib/use.sh"
# shellcheck source=lib/loadbalancer.sh
source "$_SAAS_CLUSTER_DIR/lib/loadbalancer.sh"
# shellcheck source=lib/kubeconfig.sh
source "$_SAAS_CLUSTER_DIR/lib/kubeconfig.sh"

_saas_cluster_help() {
    cat <<'EOF'
Usage: saas cluster SUBCOMMAND [OPTIONS]

Manage local Kubernetes clusters with kind: multiple simultaneous
clusters, LoadBalancer Services (MetalLB), and persistent storage that
works across several nodes. Also reachable as 'saas k8s', a pure alias.

Subcommands:
  create                     Create a new cluster
  delete                     Delete a cluster
  list, ls                   List existing clusters
  status                     Show a cluster's status
  use, switch                Switch the active kubectl context
  deploy-loadbalancer, lb    Install/reinstall MetalLB on an existing
                             cluster
  kubeconfig                 Print a cluster's kubeconfig
  expose add|list|remove     Publish specific services of an already
                             existing cluster on the LAN (or withdraw
                             those publications), see 'saas cluster
                             expose --help'

See 'saas cluster SUBCOMMAND --help' for each one's options.

Environment variables:
  SAAS_CLUSTER_NAME             Default name (autogenerated if omitted)
  SAAS_CLUSTER_WORKERS          Default number of workers (default: 1)
  SAAS_CLUSTER_IMAGE            Default kind node image
  SAAS_CLUSTER_LOADBALANCER     true/false, install MetalLB by default (default: true)
  SAAS_CLUSTER_STORAGE_FIX      true/false, multi-node storage fix in local-path mode (default: true)
  SAAS_CLUSTER_STORAGE_MODE     local-path|nfs (default: local-path)
  SAAS_CLUSTER_STORAGE_DIR      Host directory for storage data (default: ~/.local/share/kind-cluster)
  SAAS_CLUSTER_EXPOSE_MODE      none|ingress-nginx|gateway-api (default: none)
  SAAS_CLUSTER_LB_POOL_SIZE     Number of IPs per MetalLB pool (default: 10)
  SAAS_CLUSTER_NON_INTERACTIVE  true/false, disable interactive prompts (default: false)

Examples:
  saas cluster create
  saas cluster create --name my-cluster --workers 2
  saas cluster list
  saas cluster status my-cluster
  saas cluster use my-cluster
  saas cluster kubeconfig my-cluster > kubeconfig.yaml
  saas cluster expose add my-cluster --service my-service --host-port 8080
  saas cluster delete my-cluster --yes
EOF
}

_saas_cluster() {
    local subcommand="${1:-}"
    [ $# -gt 0 ] && shift

    case "$subcommand" in
        create)
            _saas_cluster_check_deps core || return 1
            _saas_cluster_create "$@"
            ;;
        delete)
            _saas_cluster_check_deps core || return 1
            _saas_cluster_delete "$@"
            ;;
        list|ls)
            _saas_cluster_check_deps core || return 1
            _saas_cluster_list "$@"
            ;;
        status)
            _saas_cluster_check_deps core || return 1
            _saas_cluster_status "$@"
            ;;
        use|switch)
            _saas_cluster_check_deps core || return 1
            _saas_cluster_use "$@"
            ;;
        deploy-loadbalancer|lb)
            _saas_cluster_check_deps full || return 1
            _saas_cluster_deploy_loadbalancer "$@"
            ;;
        kubeconfig)
            _saas_cluster_check_deps core || return 1
            _saas_cluster_kubeconfig "$@"
            ;;
        expose)
            _saas_cluster_check_deps core || return 1
            _saas_cluster_expose "$@"
            ;;
        ""|-h|--help|help)
            _saas_cluster_help
            ;;
        *)
            _saas_log_err "Unknown subcommand: 'cluster ${subcommand}'"
            _saas_cluster_help >&2
            return 1
            ;;
    esac
}
